apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "sdc.labels" . | nindent 4 }}
  name: allow-traffic-to-apiserver-extension
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0 # Can be made more restrictive by only allowing from control plane node IPs
      ports:
        - port: api-service
          protocol: TCP
  podSelector:
    matchLabels:
      {{- include "sdc.selectorLabels" . | indent 6 }}
  policyTypes:
    - Ingress
