apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config-store
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdc.labels" . | nindent 4 }}
spec:
  accessModes:
    {{ toYaml .Values.configServer.persistentVolume.accessModes | indent 4 }}
  resources:
    requests:
      storage: "{{ .Values.configServer.persistentVolume.size }}"
