apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-schema-store
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdc.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.schemaServer.persistentVolume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: "{{ .Values.schemaServer.persistentVolume.size }}"
