apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-schema-store
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
{{ toYaml .Values.schemaServer.persistentVolume.accessModes | indent 4 }}
  resources:
    requests:
      storage: "{{ .Values.schemaServer.persistentVolume.size }}"
