apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-workspace-store
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
{{ toYaml .Values.workspace.persistentVolume.accessModes | indent 4 }}
  resources:
    requests:
      storage: "{{ .Values.workspace.persistentVolume.size }}"