{{- if and (eq .Values.rbac.create true) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sdc-api-server-clusterrolebinding
  labels:
    {{- include "sdc.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sdc-api-server-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ .Values.apiServer.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end -}}