{{- if and (eq .Values.rbac.create true) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sdc-controller-metrics-auth-role
  labels:
    {{- include "sdc.labels" . | nindent 4 }}
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["subjectaccessreviews.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
{{- end -}}
