{{- if and (eq .Values.rbac.create true) }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregated-apiserver-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdc.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
{{- end -}}
