{{- if and (eq .Values.rbac.create true) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-server-clusterrolebinding
  labels:
    {{- include "sdc.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: config-server-clusterrole
subjects:
- kind: ServiceAccount
  name: config-server
  namespace: {{ .Release.Namespace }}
{{- end -}}
