{{- if and .Values.rbac.create .Values.serviceAccount.create -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
