apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: config-server
spec:
  ports:
  - name: api-service
    port: 6443
    targetPort: api-service
  selector:
    app.kubernetes.io/name: config-server
