apiVersion: v1
kind: Service
metadata:
  name: data-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: config-server
spec:
  ports:
  - name: data-service
    port: 56000
    protocol: TCP
    targetPort: data-service
  selector:
    sdcio.dev/data-server: "true"
