apiVersion: v1
kind: Service
metadata:
  name: config-server-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdc.labels" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "sdc.selectorLabels" . | indent 4 }}
