apiVersion: v1
kind: Service
metadata:
  name: schema-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdc.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-server-controller
spec:
  ports:
  - name: data-service
    port: 56000
    protocol: TCP
    targetPort: data-service
  clusterIP: None
  selector:
    {{- include "sdc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: data-server-controller
    sdcio.dev/schema-server: "true"
