apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdc.labels" . | nindent 4 }}
spec:
  ports:
  - name: api-service
    port: 6443
    targetPort: api-service
  selector:
    {{- include "sdc.selectorLabels" . | indent 4 }}
