apiVersion: v1
kind: Service
metadata:
  name: config-server-target-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdc.labels" . | nindent 4 }}
    app.kubernetes.io/component: sdc-controller
spec:
  ports:
  - name: targetmetrics
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "sdc.selectorLabels" . | indent 4 }}
    app.kubernetes.io/component: sdc-controller
