apiVersion: v1
kind: Service
metadata:
  name: data-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdc.labels" . | nindent 4 }}
spec:
  ports:
  - name: data-service
    port: 56000
    protocol: TCP
    targetPort: data-service
  selector:
    {{- include "sdc.selectorLabels" . | indent 4 }}
    sdcio.dev/data-server: "true"
