apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-server-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdc.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-server-controller
spec:
  replicas: {{ .Values.dataServer.replicas }}
  selector:
    matchLabels:
      {{- include "sdc.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: data-server-controller
  template:
    metadata:
      labels:
        {{- include "sdc.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: data-server-controller
        sdcio.dev/data-server: "true"
        sdcio.dev/schema-server: "true"
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      serviceAccountName: {{ .Values.dataServer.serviceAccount.name }}
      containers:
      - name: controller
        image: {{ include "data-server-controller.image" . }}
        imagePullPolicy: Always
        command:
        - /app/controller
        {{- range $key, $value := .Values.dataServer.controller.extraArgs }}
          {{- if $value }}
          - "--{{ $key }}={{ $value }}"
          {{- else }}
          - "--{{ $key }}"
          {{- end }}
        {{- end }}
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: "NODE_NAME"
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: "NODE_IP"
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: LOCAL_DATASERVER
          value: "true"
        - name: METRIC_PORT
          value: "8443"
        {{- range $key, $value := .Values.dataServer.controller.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        volumeMounts:
        - name: schema-store
          mountPath: /schemas
        resources:
          {{- toYaml .Values.dataServer.controller.resources | nindent 10 }}
      - name: data-server
        image: {{ include "data-server-server.image" . }}
        imagePullPolicy: Always
        command:
        - /app/data-server
        args:
        - "--config=/config/data-server.yaml"
        {{- range $key, $value := .Values.dataServer.server.extraArgs }}
          {{- if $value }}
          - "--{{ $key }}={{ $value }}"
          {{- else }}
          - "--{{ $key }}"
          {{- end }}
        {{- end }}
        ports:
        - name: data-service
          containerPort: 56000
        volumeMounts:
        - name: data-server-config
          mountPath: /config
        - name: cache
          mountPath: /cached/caches
        - name: schema-db
          mountPath: /schemadb
        - name: schema-store
          mountPath: /schemas
        resources:
          {{- toYaml .Values.dataServer.server.resources | nindent 10 }}
      volumes:
      - name: data-server-config
        configMap:
          name: data-server
      - name: cache
        emptyDir:
          sizeLimit: 10Gi
      - name: schema-db # persistent schema obj from the parsed yang files
        persistentVolumeClaim:
          claimName: pvc-schema-db
      - name: schema-store # yang file from git
        persistentVolumeClaim:
          claimName: pvc-schema-store
