apiVersion: v1
kind: Secret
metadata:
  name: config-server-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
type: kubernetes.io/service-account-token